package com.mrfurkisan.core.security.authorization;


public enum DomainName {
    
    PRODUCT_MANAGER,
    PRODUCT_OWNER,
    DEMO_OWNER,
    GUEST,
    SHIPMENT_MANAGER,
    SHIPMENT_WORKER,
    PAYMENT_MANAGER,
    PAYMENT_WORKER,
    USER_MANAGER,
    USER,
    CUSTOMER,
    CUSTOMER_MANAGER,
    STUDENT,
    TEACHER,
    STOCK_MANAGER,
    EMPLOYEE_MANAGER,
    ACOUNT_MANAGER,
    PARTICIPANT,
    ROOM_MANAGER,
    ROOM_MEMBER,
    TEAM_MANAGER,
    TEAM_MEMBER,
    AUTHOR,
    JUNIOUR_AUTHOR,
    READER,
    PRESCRİPTİVE,
    NORMAL
}
